type Query {
  users(filter: UserFilter, pagination: PaginationInput!): [User!]
}

type User {
  userId: String!
  name: String!
  email: String!
}

input UserFilter {
  name: String
  email: String
}
